import React, { useCallback, useEffect, useState } from 'react';
import { Box, Button, Chip, Grid, MenuItem, Paper, Select, Typography } from '@material-ui/core';
import { OpenInNew as LaunchIcon, Refresh as RefreshIcon, Storage as StorageIcon } from '@material-ui/icons';
import { BACKEND_URL, fetchJson } from '../apiClient';

interface Workload { id: string; name: string; image: string; status: string; uptime: string; }
interface Point { timestamp: number; value: number; }
interface Telemetry { available: boolean; message?: string; workload?: Workload; health: string; replicas: string; restarts: string; queries: Record<string, string>; metrics: Record<string, Point[]>; grafanaUrl?: string; }
interface Status { prometheus: string; grafana: string; targets: string; }
const cards = [['cpu', 'CPU UTILIZATION', '%', '#38bdf8'], ['memory', 'MEMORY USAGE', 'MiB', '#a78bfa'], ['networkRx', 'NETWORK RX', 'KiB/s', '#34d399'], ['networkTx', 'NETWORK TX', 'KiB/s', '#fbbf24']] as const;

const LineChart = ({ points, color }: { points: Point[]; color: string }) => {
  if (!points.length) return <Typography variant="body2" style={{ color: '#94a3b8', padding: '42px 0' }}>No telemetry available for this workload</Typography>;
  const values = points.map(p => p.value), min = Math.min(...values), span = Math.max(...values) - min || 1;
  const line = points.map((p, i) => `${i / Math.max(points.length - 1, 1) * 100},${92 - (p.value - min) / span * 78}`).join(' ');
  return <Box><svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{ width: '100%', height: 155 }}><polyline fill="none" stroke={color} strokeWidth="2" vectorEffect="non-scaling-stroke" points={line} /></svg><Typography variant="caption" style={{ color: '#64748b' }}>Live Prometheus range query</Typography></Box>;
};

export const ObservabilityUnifiedView: React.FC = () => {
  const [workloads, setWorkloads] = useState<Workload[]>([]), [workloadId, setWorkloadId] = useState(''), [range, setRange] = useState('15m'), [status, setStatus] = useState<Status>({ prometheus: 'CHECKING', grafana: 'CHECKING', targets: 'Checking targets…' }), [telemetry, setTelemetry] = useState<Telemetry | null>(null), [loading, setLoading] = useState(false);
  const load = useCallback(async () => {
    setLoading(true); try {
      const [s, w] = await Promise.all([fetchJson(`${BACKEND_URL}/api/observability/status`, {}, 5000), fetchJson(`${BACKEND_URL}/api/observability/workloads`, {}, 5000)]);
      if (s?.status) setStatus(s.status); const next = w?.workloads || []; setWorkloads(next);
      const selected = next.some((x: Workload) => x.id === workloadId) ? workloadId : (next[0]?.id || ''); if (selected !== workloadId) setWorkloadId(selected);
      if (selected) { const data = await fetchJson(`${BACKEND_URL}/api/observability/telemetry?workloadId=${encodeURIComponent(selected)}&range=${range}`, {}, 8000); setTelemetry(data?.telemetry || { available: false, message: 'Telemetry request failed', health: 'UNAVAILABLE', replicas: 'N/A', restarts: 'N/A', queries: {}, metrics: {} }); } else setTelemetry(null);
    } catch { setTelemetry({ available: false, message: 'Prometheus is unavailable', health: 'UNAVAILABLE', replicas: 'N/A', restarts: 'N/A', queries: {}, metrics: {} }); } finally { setLoading(false); }
  }, [workloadId, range]);
  useEffect(() => { load(); const timer = window.setInterval(load, 10000); return () => window.clearInterval(timer); }, [load]);
  const badge = (value: string) => <Chip size="small" label={value} style={{ color: ['CONNECTED', 'HEALTHY'].includes(value) ? '#86efac' : '#fca5a5', background: ['CONNECTED', 'HEALTHY'].includes(value) ? '#166534' : '#7f1d1d', fontWeight: 700 }} />;
  return <Box p={3} style={{ background: '#0b0f19', minHeight: '100vh', color: '#f8fafc' }}>
    <Box display="flex" justifyContent="space-between" alignItems="center" flexWrap="wrap" mb={3} style={{ gap: 16 }}><Box display="flex" alignItems="center"><StorageIcon style={{ color: '#38bdf8', fontSize: 34, marginRight: 12 }} /><Box><Typography variant="h5" style={{ fontWeight: 800 }}>Observability & Telemetry Center</Typography><Typography variant="body2" style={{ color: '#94a3b8' }}>Workload-scoped, live Prometheus telemetry.</Typography></Box></Box><Box display="flex" style={{ gap: 10 }} flexWrap="wrap"><Select value={workloadId} onChange={e => setWorkloadId(e.target.value as string)} displayEmpty variant="outlined" style={{ background: '#1e293b', color: '#f8fafc', minWidth: 190, height: 40 }}><MenuItem value="" disabled>{workloads.length ? 'Select workload' : 'No workloads available'}</MenuItem>{workloads.map(w => <MenuItem key={w.id} value={w.id}>{w.name}</MenuItem>)}</Select><Select value={range} onChange={e => setRange(e.target.value as string)} variant="outlined" style={{ background: '#1e293b', color: '#f8fafc', height: 40 }}>{['5m', '15m', '30m', '1h'].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</Select><Button variant="outlined" onClick={load} disabled={loading} startIcon={<RefreshIcon />} style={{ color: '#38bdf8', borderColor: '#0284c7' }}>Refresh</Button><Button variant="contained" href={telemetry?.grafanaUrl || 'http://localhost:3001'} target="_blank" startIcon={<LaunchIcon />} style={{ background: '#0284c7', color: '#fff' }}>Open Grafana</Button></Box></Box>
    <Grid container spacing={2} style={{ marginBottom: 24 }}>{[['PROMETHEUS', status.prometheus], ['GRAFANA', status.grafana], ['TELEMETRY TARGETS', status.targets], ['TELEMETRY', telemetry?.health || 'NO DATA']].map(([label, value]) => <Grid item xs={12} sm={6} md={3} key={label}><Paper style={{ padding: 16, background: '#1e293b' }}><Typography variant="caption" style={{ color: '#94a3b8', fontWeight: 700 }}>{label}</Typography><Box mt={1}>{label === 'TELEMETRY TARGETS' ? <Typography style={{ color: '#f8fafc', fontWeight: 700 }}>{value}</Typography> : badge(value)}</Box></Paper></Grid>)}</Grid>
    <Paper style={{ padding: 18, background: '#1e293b', marginBottom: 24 }}><Typography variant="subtitle1" style={{ fontWeight: 800 }}>Selected workload</Typography>{telemetry?.workload ? <Grid container spacing={2} style={{ marginTop: 4 }}><Grid item xs={6} md={3}><Typography color="textSecondary">Service</Typography><Typography>{telemetry.workload.name}</Typography></Grid><Grid item xs={6} md={3}><Typography color="textSecondary">Status</Typography><Typography>{telemetry.workload.status}</Typography></Grid><Grid item xs={6} md={3}><Typography color="textSecondary">Running replicas</Typography><Typography>{telemetry.replicas}</Typography></Grid><Grid item xs={6} md={3}><Typography color="textSecondary">Restart count</Typography><Typography>{telemetry.restarts}</Typography></Grid></Grid> : <Typography style={{ color: '#94a3b8', marginTop: 8 }}>{workloads.length ? telemetry?.message : 'No workloads available'}</Typography>}</Paper>
    {!telemetry?.available && workloadId && <Paper style={{ padding: 18, background: '#3f1d1d', color: '#fecaca', marginBottom: 24 }}>{telemetry?.message || 'No telemetry available for this workload'}</Paper>}
    <Grid container spacing={2}>{cards.map(([key, title, unit, color]) => { const points = telemetry?.metrics[key] || [], latest = points.length ? points[points.length - 1].value.toFixed(key === 'memory' ? 1 : 2) : 'No data'; return <Grid item xs={12} md={6} key={key}><Paper style={{ padding: 18, background: '#1e293b', minHeight: 245 }}><Box display="flex" justifyContent="space-between"><Typography variant="subtitle2" style={{ color: '#94a3b8', fontWeight: 800 }}>{title}</Typography><Typography style={{ color, fontWeight: 800 }}>{latest}{points.length ? ` ${unit}` : ''}</Typography></Box><LineChart points={points} color={color} /><Typography variant="caption" style={{ color: '#64748b', wordBreak: 'break-all' }}>{telemetry?.queries[key]}</Typography></Paper></Grid>; })}</Grid>
  </Box>;
};
