site_name: Internal Developer Platform (IDP) Documentation
site_description: Technical architecture, setup, operation, and security documentation for the Backstage IDP.

plugins:
  - techdocs-core

nav:
  - Overview: index.md
  - Architecture: architecture/idp-architecture.md
  - Setup & Deployment: setup/aws-deployment.md
  - Operations & Troubleshooting: operations/troubleshooting.md
